//Login action Types 

export const LOGIN_START ='LOGIN_START'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'

export const AUTHENTICATE_USER ='AUTHENTICATE_USER'
export const LOG_OUT ='LOG_OUT'

//Signup

export const SIGNUP_START='SIGN_START'
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS'
export const SIGNUP_FAILED='SIGNUP_FAILED'

//FORM

export const GET_USER_VIA_DEPARTMENT ='GET_FORM_VIA_DEPARTMENT'
